### ISSUE TITLE
wru should be a `devDependency`

### ISSUE THREAD

**Issue by pjeby** [WebReflection/redefine#4]
Since `wru` isn't used at runtime, it should be listed in `package.json` as a `devDependency`, not a `dependency`.  It will still be installed if you do `npm install` in the development directory, but won't be installed in production deployments.

**Comment by WebReflection** [comment]
I think you might want to consider the more recent, updated, actively maintained [es-class](https://github.com/WebReflection/es-class#es-class) ... this one is quite old and not so popular way to enrich classes, we can have much more and be future proof with ES6, 7, and whatever comes next.

**Comment by WebReflection** [comment]
btw, moved wru into devDependencies.

Best Regards

**Comment by pjeby** [comment]
Thanks.  I code in CoffeeScript, so all I'm actually using is redefine.later, and the convenient shorthand for Object.defineProperties.  For what I'm doing, lazyval is too narrow, and es-class too broad; redefine is "just right".  ;-)

**Comment by WebReflection** [comment]
fair enough :-)
